config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
   devise_for :users
   devise_scope :user do
  authenticated :user do
    root 'dashboards#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
resources :requests
 resources :clinics
 resources :hospitals
 resources :doctors
 resources :records
 resources :dashboards
 resources :patients


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinic.rb
class Clinic < ApplicationRecord
  has_many :doctors
 has_many :records
 validates :clinicname, :clinicaddress, :clinicnumber, presence: true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
   has_many :requests
   validates :clinic ,:docname, :docaddress, :docnumber, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :requests
  has_many :records
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :requests
    has_many :medical_records
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :requests
  validates :request, :hospitals , presence: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ActiveRecord::Base
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:clinicname, :clinicaddress, :clinicnumber)
    end
end

app/controllers/doc_user.rb
require 'singleton'
class DocUser
  include Singleton

  attr_accessor :doctor, :clinic, :current_patient,
                :medical_records, :appointments,
                :requests

  # initialise doctor/user singleton by passing in
  # the doctor
  def init(doctor)
    @doctor = doctor
    @clinic = @doctor.clinic
    @medical_records = []

    @requests = []
  end

  # use custom gem to fill out doctor's appointments


  # use custom gem to fill out relevant patient's medial records
  

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all

  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new

  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:docname, :docaddress, :docnumber, :clinic)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:description, :prescription, :infection, :appointment, :Obs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/clinics/_form.html.erb
<%= form_with(model: clinic, local: true) do |form| %>
  <% if clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% clinic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :clinicname %>
    <%= form.text_field :clinicname, id: :clinic_clinicname %>
  </div>

  <div class="field">
    <%= form.label :clinicaddress %>
    <%= form.text_field :clinicaddress, id: :clinic_clinicaddress %>
  </div>

  <div class="field">
    <%= form.label :clinicnumber %>
    <%= form.text_field :clinicnumber, id: :clinic_clinicnumber %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing Clinic</h1>

<%= render 'form', clinic: @clinic %>

<%= link_to 'Show', @clinic %> |
<%= link_to 'Back', clinics_path %>

app/views/clinics/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Clinics</h1>

<table>
  <thead>
    <tr>
      <th>Clinicname</th>
      <th>Clinicaddress</th>
      <th>Clinicnumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clinics.each do |clinic| %>
      <tr>
        <td><%= clinic.clinicname %></td>
        <td><%= clinic.clinicaddress %></td>
        <td><%= clinic.clinicnumber %></td>
        <td><%= link_to 'Show', clinic %></td>
        <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
        <td><%= link_to 'Destroy', clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><button><%= link_to 'New Clinic', new_clinic_path %></button></td>

app/views/clinics/new.html.erb
<h1>New Clinic</h1>

<%= render 'form', clinic: @clinic %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clinicname:</strong>
  <%= @clinic.clinicname %>
</p>

<p>
  <strong>Clinicaddress:</strong>
  <%= @clinic.clinicaddress %>
</p>

<p>
  <strong>Clinicnumber:</strong>
  <%= @clinic.clinicnumber %>
</p>

<%= link_to 'Edit', edit_clinic_path(@clinic) %> |
<%= link_to 'Back', clinics_path %>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :doctor_name %>
    <%= form.text_field :docname, id: :doctor_docname %>
  </div>

  <div class="field">
    <%= form.label :doctor_address %>
    <%= form.text_field :docaddress, id: :doctor_docaddress %>
  </div>

  <div class="field">
    <%= form.label :doctor_number %>
    <%= form.text_field :docnumber, id: :doctor_docnumber %>
  </div>

  <div class="field">
    <%= form.label :clinic_name %>
    <%= form.text_field :clinic, id: :doctor_clinic %>
  </div>
  </br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>
</br>
<table>
  </br>
  <thead>
    </br>
    <tr>
      <th>Docname</th>
      <th>Docaddress</th>
      <th>Docnumber</th>
      <th>Clinic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.docname %></td>
        <td><%= doctor.docaddress %></td>
        <td><%= doctor.docnumber %></td>
        <td><%= doctor.clinic %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><button><%= link_to 'New Doctor', new_doctor_path %></button></td>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Docname:</strong>
  <%= @doctor.docname %>
</p>

<p>
  <strong>Docaddress:</strong>
  <%= @doctor.docaddress %>
</p>

<p>
  <strong>Docnumber:</strong>
  <%= @doctor.docnumber %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @doctor.clinic %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :record_description %>
  </div>

  <div class="field">
    <%= form.label :prescription %>
    <%= form.text_field :prescription, id: :record_prescription %>
  </div>

  <div class="field">
    <%= form.label :infection %>
    <%= form.text_field :infection, id: :record_infection %>
  </div>

  <div class="field">
    <%= form.label :appointment %>
    <%= form.text_field :appointment, id: :record_appointment %>
  </div>

  <div class="field">
    <%= form.label :Obs %>
    <%= form.text_field :Obs, id: :record_Obs %>
  </div>

  <div class="field">
      <%= form.label :patient %>
      <%= form.select :patient, options_for_select(Patient.all.map{|p| p.name}), { :include_blank => true, :prompt => 'Select Patient'} %>
    </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Prescription</th>
      <th>Infection</th>
      <th>Appointment</th>
      <th>Obs</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.description %></td>
        <td><%= record.prescription %></td>
        <td><%= record.infection %></td>
        <td><%= record.appointment %></td>
        <td><%= record.Obs %></td>
        <td><%= record.patient %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><button><%= link_to 'New Record', new_record_path %></button></td>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @record.description %>
</p>

<p>
  <strong>Prescription:</strong>
  <%= @record.prescription %>
</p>

<p>
  <strong>Infection:</strong>
  <%= @record.infection %>
</p>

<p>
  <strong>Appointment:</strong>
  <%= @record.appointment %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @record.Obs %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @record.patient %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>