config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
   devise_for :users
   devise_scope :user do
  authenticated :user do
    root 'dashboards#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
resources :requests
 resources :clinics
 resources :hospitals
 resources :doctors
 resources :records
 resources :dashboards
 resources :patients


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinic.rb
class Clinic < ApplicationRecord
  has_many :doctors
 has_many :records
 validates :clinicname, :clinicaddress, :clinicnumber, presence: true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
   has_many :requests
   validates :clinic ,:docname, :docaddress, :docnumber, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :requests
  has_many :records
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :requests
    has_many :medical_records
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :requests
  validates :request, :hospitals , presence: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ActiveRecord::Base
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:clinicname, :clinicaddress, :clinicnumber)
    end
end

app/controllers/doc_user.rb
require 'singleton'
class DocUser
  include Singleton

  attr_accessor :doctor, :clinic, :current_patient,
                :medical_records, :appointments,
                :requests

  # initialise doctor/user singleton by passing in
  # the doctor
  def init(doctor)
    @doctor = doctor
    @clinic = @doctor.clinic
    @medical_records = []

    @requests = []
  end

  # use custom gem to fill out doctor's appointments


  # use custom gem to fill out relevant patient's medial records
  

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all

  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new

  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:docname, :docaddress, :docnumber, :clinic)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :address, :number, :birthday, :infection, :injury, :observations)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :patient_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :patient_address %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :patient_number %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday, id: :patient_birthday %>
  </div>

  <div class="field">
    <%= form.label :infection %>
    <%= form.text_field :infection, id: :patient_infection %>
  </div>

  <div class="field">
    <%= form.label :injury %>
    <%= form.text_field :injury, id: :patient_injury %>
  </div>

  <div class="field">
    <%= form.label :observations %>
    <%= form.text_field :observations, id: :patient_observations %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>|
<%= link_to 'Create Request', href="http://0.0.0.0:3000/requests" %> |

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Patients</h1>
<table>
  <thead>
    <tr colspan="3"></th>
      <th>Name</th>
      <th>Address</th>
      <th>Number</th>
      <th>Birthday</th>
      <th>infection</th>
      <th>Injury</th>
      <th>Observations</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody colspan="3">
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.address %></td>
        <td><%= patient.number %></td>
        <td><%= patient.birthday %></td>
        <td><%= patient.infection %></td>
        <td><%= patient.injury %></td>
        <td><%= patient.observations %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<td><button><%= link_to 'New Patient', new_patient_path %></button></td>
<td><button><%= link_to 'Create Request', href="http://0.0.0.0:3000/requests" %></button></td>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>|

<%= link_to 'Back', patients_path %>|

<%= link_to 'Create Request', href="http://0.0.0.0:3000/requests" %> |

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Number:</strong>
  <%= @patient.number %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @patient.birthday %>
</p>

<p>
  <strong>infection:</strong>
  <%= @patient.infection %>
</p>

<p>
  <strong>Injury:</strong>
  <%= @patient.injury %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @patient.observations %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>