config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
   devise_for :users
   devise_scope :user do
  authenticated :user do
    root 'dashboards#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
resources :requests
 resources :clinics
 resources :hospitals
 resources :doctors
 resources :records
 resources :dashboards
 resources :patients


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinic.rb
class Clinic < ApplicationRecord
  has_many :doctors
 has_many :records
 validates :clinicname, :clinicaddress, :clinicnumber, presence: true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
   has_many :requests
   validates :clinic ,:docname, :docaddress, :docnumber, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :requests
  has_many :records
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :requests
    has_many :medical_records
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :requests
  validates :request, :hospitals , presence: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ActiveRecord::Base
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/doc_user.rb
require 'singleton'
class DocUser
  include Singleton

  attr_accessor :doctor, :clinic, :current_patient,
                :medical_records, :appointments,
                :requests

  # initialise doctor/user singleton by passing in
  # the doctor
  def init(doctor)
    @doctor = doctor
    @clinic = @doctor.clinic
    @medical_records = []

    @requests = []
  end

  # use custom gem to fill out doctor's appointments


  # use custom gem to fill out relevant patient's medial records
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Healthcare Management</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= image_tag('/assets/image.jpg', width: '100px') %>

    <%= link_to 'Home', dashboards_path %>
    <%= link_to 'Patients', patients_path %>
    <%= link_to 'Doctors', doctors_path %>
    <%= link_to 'Clinics', clinics_path %>
    <%= link_to 'Hospitals',hospitals_path %>
    <%= link_to 'Requests', requests_path %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>